---
- name: Print text
  hosts: all
  become: yes
  gather_facts: yes
  
  tasks:
    - debug:
        msg: "Just saying hello wtih ansible from AWX!"
    
    - name: Get UUID of share SR
      command: xe sr-list name-label="VMs" --minimal
      register: sruuid

    - name: Get UUID of template
      command: xe template-list name-label="ubuntu 22.04-cloudimg-ssh-tools" --minimal
      register: templateuuid
      
    - name: Get UUID of network
      command: xe network-list name-label="Host internal management network"" --minimal
      register: networkuuid
      
    - debug:
        msg: "The template UUID is {{ networkuuid.stdout }}"
