---
- name: Print text
  hosts: all
  become: yes
  gather_facts: yes
  
  tasks:
    - debug:
        msg: "Just saying hello wtih ansible from AWX!"
    
    - name: Get UUID of share SR
      command: xe sr-list name-label="VMs" --minimal
      register: sruuid

    - name: Get UUID of template
      command: xe template-list name-label="ubuntu 22.04-cloudimg-ssh-tools" --minimal
      register: templateuuid
      
    - name: Get UUID of network
      command: xe network-list name-label="Host internal management network" --minimal
      register: networkuuid
   
    - name: Create new VM
      command: xe vm-install template={{ templateuuid.stdout  }} new-name-label={{ vmname }} sr-uuid={{ sruuid.stdout }}
      register: vmuuid
      
    - name: Ge UUID pf VIF
      command: xe vm-vif-list vm={{ vmuuid.stdout }} --minimal
      register: vifuuid
      
    - name: Set IP Address for VM
      command: xe vif-configure-ipv4 uuid={{ vifuuid.stdout }} mode=static address={{ ipaddress }}/24 gateway={{ gateway }}
   
    - debug:
        msg: "Crated {{ vmname }} : {{ ipaddress }} : {{ gateway }}"
