---
- name: Print text
  hosts: all
  become: yes
  gather_facts: yes
  
  tasks:
    - debug:
        msg: "Just saying hello wtih ansible from AWX!"
    
    - name: Get UUID of share SR
      command: xe sr-list name-label="VMs" --minimal
      register: sruuid

    - name: Get UUID of template
      command: xe template-list name-label="AlmaLinux 9" --minimal
      register: templateuuid
      
    - name: Get UUID of network
      command: xe network-list name-label="Host internal management network" --minimal
      register: networkuuid
   
    - name: Create new VM
      command: xe vm-install template={{ templateuuid.stdout }} new-name-label={{ vmname }} sr-uuid={{ sruuid.stdout }}
      register: vmuuid
      
    - name: Boot VM and start preseed installation
      command: xe vm-start uuid={{ vmuuid.stdout }}

    - name: Get the boot time for the VM
      command: xe vm-param-get param-name=start-time uuid={{ vmuuid.stdout}}
      register: boottime
      
    - name: Get UUID pf VIF
      command: xe vm-vif-list vm={{ vmuuid.stdout }} --minimal
      register: vifuuid
      
    - name: Get IP of VM
      shell: xe vm-list params=networks uuid={{ vmuuid.stdout }} --minimal | grep -E -o '0\/ip{{ ":"}} ([0-9]+.[0-9]+.[0-9]+.[0-9]+)' | awk '{print $2}'
      register: tmpip
      until: tmpip.stdout != ""
      retries: 10
      delay: 10
   
    - debug:
        msg: "Temporary IP is {{ tmpip.stdout }}"
