---
- name: Print text
  hosts: all
  become: yes
  gather_facts: yes
  
  tasks:    
    - name: Get IP of VM
      command: xe vm-list params=networks name-label='test1' --minimal
      register: tmpip
   
    - debug:
        msg: "Temporary IP is {{ tmpip.stdout }}"
