---
- name: Print text
  hosts: all
  become: yes
  gather_facts: yes
  
  tasks:    
    - name: Get IP of VM
      command: xe vm-list params=networks name-label='test1' --minimal
      register: tmpip | grep -E -o '0\/ip{{ ":"}} ([0-9]+.[0-9]+.[0-9]+.[0-9]+)' | awk '{print $2}'
      
    - name: Extract IP from result
      shell: {{ tmpip.stdout }} | grep -E -o '0\/ip{{ ":"}} ([0-9]+.[0-9]+.[0-9]+.[0-9]+)' | awk '{print $2}'
      register: test
   
    - debug:
        msg: "Temporary IP is {{ test.stdout }}"
